### PR TITLE
Add frost depth module

### PR DESCRIPTION
**Pull request by charparr**
This PR implements the Modified Bergrenn frost depth computation in a Jupyter environment using interactive widgets to control location, climate, and soil factor inputs. The logic is identical to https://github.com/ua-snap/streamlit-frost-depth but we ditched the Streamlit interface in favor of a Jupyter deploy.

You can clone this repo and activate the environment locally (nothing fancy, but many of our envs don't have the `ipywidgets` package that is used here to interact with the frost depth computation function).

You can also try cloning this repo from a JupyterHub notebook on notebook.earthmaps.io
If you want to do that:
 - Open a new, blank notebook
 - Run this command `! git clone https://github.com/ua-snap/ardac-notebooks.git`
 - Next in a new cell run `! cd ardac-notebooks && git checkout frost_depth_module`
 - Now go back to Jupyter file browser, navigate to the frost depth notebook, let it rip

To test this PR:
 - Review the README and then read the code in `modberg.py`
 - Run the notebook, play with the sliders, watch the output change!

Non-goals
 - Fancy or visually appealing
 - Lots of explaining, etc.

### CODE REVIEW

**Comment by Joshdpaul** [comment]
Charlie,

I was able to set up and run the `Modified Berggren Frost Depth.ipynb` notebook via JupyterHub. My first time using JupyterHub, and your setup for this PR made it super easy! 

The widget seems to work as expected except for the printed result statement at the bottom. I see a single number (purple oval) that changes in response to slider adjustment. But the number in the text string below (blue oval) never changes, its stuck on the default result of 5.7. Looking at the code, I don't see how this could be the case - where is the standalone number printing from, if not the last line of the notebook cell: `print(f"Computed Modified Bergrenn Frost Depth: {frost_depth.widget.result} feet")` ???

There is no print command in any of the `modberg.py` modules, so I am confused by this behavior and unfortunately do not have any suggestions for fixing it.

image

**Comment by charparr** [comment]
Thanks Josh! I think I need to learn how to display the output with a widget that is tied to the state of the function. I think the print statement is just not dynamic at all and just displaying the same result each time. I'll see if I can rectify and fix, good catch!

**Comment by charparr** [comment]
@Joshdpaul I think I've fixed the dynamic display of the result for the frost depth computation.
Also, take a peek at the design_freezing_index module that I've tacked on to this branch - thoughts? It was a different flavor than frost depth (less academic, more code-forward).
@BobTorgerson if you can just verify that you're able to clone this on our JupyterHub that'd be great! Also I noticed that every once in a while my JupyterHub connection gets severed - maybe there is a timeout? Not urgent, but if we can close this PR then I'll start refining with more input from the rest of the team.

**Comment by Joshdpaul** [comment]
Hey Charlie, I can confirm that the display of the frost depth module has been fixed 👍!

As for the `design_freezing_index.ipynb` module, that works as well. My only comment is that there is no default value printed when opening the notebook. In other words, the sliders are set to default values (2030, 2060, 3) but there is no printed `Design Freezing Index: #### °F-days` until you move the sliders to new values. That's not a huge deal but I was initially confused like "where am I going to see the output?" and that question is not resolved until I start to play with the sliders. I would suggest adding a default value, if possible.

**Comment by charparr** [comment]
Awesome thanks for the re-review Josh! I've ticketed (#2 ) your feedback and will address here in the next branch

**Pull request merged**
